sudo: required
services:
  - docker


before_install:
  - docker build -t jvhaggard/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true jvhaggard/docker-react npm run test -- --coverage